configs:
    - configs/base.yaml # default arguments for the whole codebase
    - configs/models/r4dvb.yaml # network model configuration
    - configs/datasets/mobile_stage/dance3_obj.yaml # dataset usage configuration
    - configs/specs/optimized.yaml # specific usage configuration

dataloader_cfg:
    dataset_cfg: &dataset_cfg
        frame_sample: [0, 300, 1]

val_dataloader_cfg:
    dataset_cfg:
        <<: *dataset_cfg

model_cfg:
    sampler_cfg:
        n_points: 390516 # for surfs extraction
        bg_sampler_cfg:
            radius_shift: -2.5
            radius_max: 0.1

# prettier-ignore
exp_name: {{fileBasenameNoExtension}}
